name: Deploy to Production

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Deploy
      run: now --prod -c -t ${{ secrets.ZEIT_TOKEN }}
